# yaml-language-server: $schema=./node_modules/somod-schema/schemas/parameters/index.json

parameters:
  apigateway.http.endpoint:
    type: string
  apigateway.http.cors.allow_credentials:
    type: boolean
    default: false
  apigateway.http.cors.allow_headers:
    type: array
    items:
      type: string
    default: []
    multiple: true
  apigateway.http.cors.allow_methods:
    type: array
    items:
      type: string
    default: []
    multiple: true
  apigateway.http.cors.allow_origins:
    type: array
    items:
      type: string
    default: []
    multiple: true
  apigateway.http.cors.expose_headers:
    type: array
    items:
      type: string
    default: []
    multiple: true
  apigateway.http.cors.max_age:
    type: number
    multipleOf: 1
    default: 0
