# yaml-language-server: $schema=../node_modules/somod-schema/schemas/serverless-template/index.json

Resources:
  BaseHttpApi:
    Type: AWS::Serverless::HttpApi
    "SOMOD::Access": "public"
    "SOMOD::Output":
      default: true
      attributes: []
    Properties:
      CorsConfiguration:
        AllowCredentials:
          SOMOD::Parameter: apigateway.http.cors.allow_credentials
        AllowHeaders:
          SOMOD::Parameter: apigateway.http.cors.allow_headers
        AllowMethods:
          SOMOD::Parameter: apigateway.http.cors.allow_methods
        AllowOrigins:
          SOMOD::Parameter: apigateway.http.cors.allow_origins
        ExposeHeaders:
          SOMOD::Parameter: apigateway.http.cors.expose_headers
        MaxAge:
          SOMOD::Parameter: apigateway.http.cors.max_age

Outputs:
  apigateway.http.endpoint:
    Fn::Sub:
      - https://${apiId}.execute-api.${AWS::Region}.amazonaws.com/
      - apiId:
          SOMOD::Ref:
            resource: BaseHttpApi
