# yaml-language-server: $schema=../node_modules/somod/node_modules/@somod/schema/serverless/schemas/index.json

Resources:
  BaseHttpApi:
    Type: AWS::Serverless::HttpApi
    "SOMOD::Access": "public"
    "SOMOD::Output":
      default: true
      attributes: []
    Properties: {}

Outputs:
  apigateway.http.endpoint:
    Fn::Sub:
      - https://${apiId}.execute-api.${AWS::Region}.amazonaws.com/
      - apiId:
          SOMOD::Ref:
            resource: BaseHttpApi
