# yaml-language-server: $schema=../node_modules/somod/node_modules/@somod/schema/ui-config/schemas/index.json

env:
  NEXT_PUBLIC_SOMOD_BASE_HTTP_API_ENDPOINT:
    SOMOD::Parameter: apigateway.http.endpoint
